web:
    image: odoo:8
    volumes:
        - ./extra-addons/:/mnt/extra-addons/
    links:
        - db
    ports:
        - "8069:8069"
db:
    image: postgres:latest
    environment:
        POSTGRES_USER: odoo
        POSTGRES_PASSWORD: odoo
